name: datasets

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch: {}
  push: {}

jobs:
  data:
    runs-on: ubuntu-latest
    container: ghcr.io/investigativedata/investigraph:main
    env:
      DEBUG: true
    steps:
      - name: parse and write dd-ger-berlin
        run: "investigraph run -c datasets/dd-ger-berlin/config.yml "
